const KEY_MENU_ITEM_EXPORT = 'MENU_ITEM_EXPORT'
const KEY_SUB_MENU_FILES = 'SUB_MENU_FILES'
const KEY_MENU_ITEM_FILE_LIST = 'MENU_ITEM_FILE_LIST'
const KEY_MENU_ITEM_FILE_UPLOAD = 'MENU_ITEM_FILE_UPLOAD'
const KEY_SUB_MENU_TEMPLATES = 'SUB_MENU_TEMPLATES'
const KEY_MENU_ITEM_TEMPLATE_LIST = 'MENU_ITEM_TEMPLATE_LIST'
const KEY_MENU_ITEM_TEMPLATE_ADD = 'MENU_ITEM_TEMPLATE_ADD'
const KEY_SUB_MENU_TAGS = 'KEY_SUB_MENU_TAGS'
const KEY_MENU_ITEM_TAG_LIST = 'KEY_MENU_ITEM_TAG_LIST'
const KEY_MENU_ITEM_TAG_ADD = 'KEY_MENU_ITEM_TAG_ADD'
const ROUTER_URL_EXPORT = '/export'
const ROUTER_URL_FILE_LIST = '/file/list'
const ROUTER_URL_FILE_ADD = '/file/add'
const ROUTER_URL_TEMPLATE_LIST = '/template/list'
const ROUTER_URL_TEMPLATE_ADD = '/template/add'
const ROUTER_URL_TAG_LIST = '/tag/list'
const ROUTER_URL_TAG_ADD = '/tag/add'

export {
  KEY_MENU_ITEM_EXPORT,
  KEY_SUB_MENU_FILES,
  KEY_MENU_ITEM_FILE_LIST,
  KEY_MENU_ITEM_FILE_UPLOAD,
  KEY_SUB_MENU_TEMPLATES,
  KEY_MENU_ITEM_TEMPLATE_LIST,
  KEY_MENU_ITEM_TEMPLATE_ADD, 
  KEY_SUB_MENU_TAGS,
  KEY_MENU_ITEM_TAG_LIST,
  KEY_MENU_ITEM_TAG_ADD,
  ROUTER_URL_EXPORT,
  ROUTER_URL_FILE_LIST,
  ROUTER_URL_FILE_ADD,
  ROUTER_URL_TEMPLATE_LIST,
  ROUTER_URL_TEMPLATE_ADD, 
  ROUTER_URL_TAG_LIST,
  ROUTER_URL_TAG_ADD,
}