const SERVER_ADDRESS = `localhost`
const SERVER_PORT_NUM = 4000

const SERVER_URL_FILE_ADD = `http://${SERVER_ADDRESS}:${SERVER_PORT_NUM}/files/add`
const SERVER_URL_FILE_DELETE = `http://${SERVER_ADDRESS}:${SERVER_PORT_NUM}/files/file_delete`
const SERVER_URL_FILE_LIST_ALL = `http://${SERVER_ADDRESS}:${SERVER_PORT_NUM}/files/file_list`
const SERVER_URL_FILE_FIND_BY_NAME = `http://${SERVER_ADDRESS}:${SERVER_PORT_NUM}/files/check_exist_by_name`
const SERVER_URL_TAG_ADD = `http://${SERVER_ADDRESS}:${SERVER_PORT_NUM}/tags/add`
const SERVER_URL_TAG_LIST_ALL = `http://${SERVER_ADDRESS}:${SERVER_PORT_NUM}/tags/list_all`
const SERVER_URL_TAG_DELETE = `http://${SERVER_ADDRESS}:${SERVER_PORT_NUM}/tags/delete`
const SERVER_URL_TEMPLATE_ADD = `http://${SERVER_ADDRESS}:${SERVER_PORT_NUM}/templates/add`
const SERVER_URL_TEMPLATE_LIST_ALL = `http://${SERVER_ADDRESS}:${SERVER_PORT_NUM}/templates/list_all`
const SERVER_URL_TEMPLATE_FIND = `http://${SERVER_ADDRESS}:${SERVER_PORT_NUM}/templates/find`
const SERVER_URL_EXPORT = `http://${SERVER_ADDRESS}:${SERVER_PORT_NUM}/files/export`

export {
  SERVER_URL_FILE_ADD,
  SERVER_URL_FILE_DELETE,
  SERVER_URL_FILE_LIST_ALL,
  SERVER_URL_FILE_FIND_BY_NAME,
  SERVER_URL_TAG_ADD, 
  SERVER_URL_TAG_LIST_ALL,
  SERVER_URL_TAG_DELETE,
  SERVER_URL_TEMPLATE_ADD,
  SERVER_URL_TEMPLATE_LIST_ALL,
  SERVER_URL_TEMPLATE_FIND,
  SERVER_URL_EXPORT,
}